repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: no-commit-to-branch
        args: ["-b", "main"]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/pypa/pip-audit
    rev: v2.10.0
    hooks:
      - id: pip-audit
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.12
    hooks:
      - id: actionlint-docker
  - repo: https://github.com/uktrade/github-standards
    rev: v1.2.1 # This should be the latest github released tag, see https://github.com/uktrade/github-standards/releases for the latest tag
    hooks:
      - id: validate-security-scan
        verbose: false # This is helpful for debugging initial setup, it can be removed when the hooks are verified as working in your repository
        args: [-v] # This is helpful for debugging the hook logic, the output is shown in the git output
      - id: run-security-scan
        verbose: false
        args: [--verbose]
